[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/send-order"
  to = "/.netlify/functions/send-order"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/auth-otp"
  to = "/.netlify/functions/auth-otp"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
